# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTE3OGZjMjhmMDMwM2I3MmE2ZjVhMDVhM2M1MGU1ZjI5MDUzNGMwOTdmMTYxNzBlZjZlZmFiNWY0MGQ1NjU0N2ZmZjU2YmE0NzMxODFkZDY0MTY4MWU2NmNmNDZiMTRkNmI3M2E2NWYzOTEwNjNjZTI2OTZmYjkxNGM1OWI0MzY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
