apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: coffee
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
