apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: coffee
#common configuration shared between all applications
data:
  application.yml: |-
    springdoc:
      api-docs:
        enabled: true
    configserver:
      name:  JHipster Registry
      status: Connected to the JHipster Registry running in Kubernetes
    eureka:
      client:
        initial-instance-info-replication-interval-seconds: 15
        instance-info-replication-interval-seconds: 15
        registry-fetch-interval-seconds: 15
        fetch-registry: true
        register-with-eureka: true
        eureka-service-url-poll-interval-seconds: 15
      instance:
        lease-renewal-interval-in-seconds: 10
        registry-default-open-for-traffic-count: 0
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: OTE3OGZjMjhmMDMwM2I3MmE2ZjVhMDVhM2M1MGU1ZjI5MDUzNGMwOTdmMTYxNzBlZjZlZmFiNWY0MGQ1NjU0N2ZmZjU2YmE0NzMxODFkZDY0MTY4MWU2NmNmNDZiMTRkNmI3M2E2NWYzOTEwNjNjZTI2OTZmYjkxNGM1OWI0MzY=
    logging:
      level:
        ROOT: DEBUG
        tech.jhipster: DEBUG
        org.hibernate.SQL: DEBUG
        com.shopapp: DEBUG
  # app specific configuration
  jhipster-registry.yml: |-
    eureka:
      client:
        service-url:
          defaultZone: http://admin:${spring.security.user.password}@jhipster-registry-0.jhipster-registry.coffee.svc.cluster.local:8761/eureka/,http://admin:${spring.security.user.password}@jhipster-registry-1.jhipster-registry.coffee.svc.cluster.local:8761/eureka/
  
  gateway-prod.yml: |-
    jhipster:
      cors:
        allowed-origins: "http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200,http://localhost:56297"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count,X-$gatewayApp-alert,X-$gatewayApp-error,X-$gatewayApp-params"
        allow-credentials: true
        max-age: 1800
    spring:
      jpa:
        show-sql: true
      liquibase:
        url: jdbc:postgres://gateway:5432/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        user: postgres
        password: 123456
    
      r2dbc:
        url: r2dbc:mariadb://gateway:5432/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: postgres
        password: 123456

  shopService-prod.yml: |-
    spring:
      jpa:
        show-sql: true
      datasource:
        url: jdbc:postgres://coffee_shop:5432/coffee_shop?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: postgres
        password: 123456
        driverClassName: org.postgresql.Driver
      liquibase:
        url: jdbc:postgres://coffee_shop:5432/coffee_shop?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        user: postgres
        password: 123456
        driverClassName: org.postgresql.Driver

  orderService-prod.yml: |-
    spring:
      jpa:
        show-sql: true
      datasource:
        url: jdbc:postgres://coffee_shop:5432/coffee_shop?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: postgres
        password: 123456
        driverClassName: org.postgresql.Driver
      liquibase:
        url: jdbc:postgres://coffee_shop:5432/coffee_shop?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        user: postgres
        password: 123456
        driverClassName: org.postgresql.Driver
    coffee:
      order:
        secret: 2N%wwgmNr?8Z9PY8@6jPz4YR&Pyq


